<a href="https://colab.research.google.com/github/hardikcode-creator/NLP/blob/main/NLP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## BAG of Words


In [4]:

import pandas as pd


In [6]:
df=pd.read_csv('spam.csv',encoding='latin1')
df=df[['v1','v2']]
df.columns=['label','message']
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
## Preprocessing
import re
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()


In [9]:
corpus=[]
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z]',' ',df['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [10]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [11]:
## BOW
from sklearn.feature_extraction.text import CountVectorizer
# max_features------> no of top features to pick based on frequency of vocabulary
cv=CountVectorizer(max_features=2500,binary=True)
X=cv.fit_transform(corpus).toarray()

In [12]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
X.shape

(5572, 2500)

## N grams

In [14]:
cv.vocabulary_

{'go': 829,
 'point': 1598,
 'crazi': 479,
 'avail': 165,
 'bugi': 310,
 'great': 853,
 'world': 2436,
 'la': 1116,
 'cine': 401,
 'got': 844,
 'wat': 2358,
 'ok': 1466,
 'lar': 1128,
 'joke': 1057,
 'wif': 2400,
 'oni': 1474,
 'free': 769,
 'entri': 643,
 'wkli': 2422,
 'comp': 435,
 'win': 2404,
 'cup': 493,
 'final': 726,
 'tkt': 2206,
 'st': 2055,
 'may': 1274,
 'text': 2168,
 'receiv': 1752,
 'question': 1708,
 'std': 2066,
 'txt': 2263,
 'rate': 1733,
 'appli': 118,
 'dun': 605,
 'say': 1851,
 'earli': 609,
 'alreadi': 82,
 'nah': 1387,
 'think': 2182,
 'goe': 832,
 'usf': 2304,
 'live': 1184,
 'around': 137,
 'though': 2188,
 'freemsg': 771,
 'hey': 908,
 'darl': 512,
 'week': 2373,
 'word': 2433,
 'back': 181,
 'like': 1173,
 'fun': 789,
 'still': 2068,
 'tb': 2144,
 'xxx': 2465,
 'send': 1888,
 'rcv': 1736,
 'even': 657,
 'brother': 299,
 'speak': 2037,
 'treat': 2241,
 'per': 1543,
 'request': 1785,
 'mell': 1291,
 'oru': 1492,
 'minnaminungint': 1315,
 'nurungu': 1452,
 'vet

In [15]:
## BOW with n grams
from sklearn.feature_extraction.text import CountVectorizer
# max_features------> no of top features to pick based on frequency of vocabulary
cv=CountVectorizer(max_features=2500,binary=True,ngram_range=(1,2))
X_bow=cv.fit_transform(corpus).toarray()

In [16]:

X_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [17]:
X_bow.shape

(5572, 2500)

In [18]:
cv.vocabulary_

{'go': 804,
 'point': 1608,
 'crazi': 451,
 'avail': 113,
 'bugi': 228,
 'great': 858,
 'world': 2436,
 'la': 1093,
 'cine': 343,
 'got': 842,
 'wat': 2347,
 'ok': 1473,
 'lar': 1105,
 'joke': 1061,
 'wif': 2402,
 'oni': 1494,
 'free': 727,
 'entri': 611,
 'wkli': 2426,
 'comp': 395,
 'win': 2407,
 'cup': 465,
 'final': 686,
 'st': 1972,
 'may': 1271,
 'text': 2088,
 'receiv': 1709,
 'question': 1664,
 'std': 1987,
 'txt': 2208,
 'rate': 1680,
 'appli': 78,
 'free entri': 734,
 'entri wkli': 613,
 'std txt': 1988,
 'txt rate': 2214,
 'rate appli': 1682,
 'dun': 576,
 'say': 1800,
 'earli': 582,
 'alreadi': 51,
 'nah': 1385,
 'think': 2115,
 'goe': 822,
 'usf': 2278,
 'live': 1173,
 'around': 89,
 'though': 2123,
 'freemsg': 747,
 'hey': 924,
 'darl': 484,
 'week': 2371,
 'word': 2432,
 'back': 130,
 'like': 1159,
 'fun': 764,
 'still': 1990,
 'tb': 2066,
 'xxx': 2466,
 'send': 1829,
 'rcv': 1687,
 'even': 620,
 'brother': 217,
 'speak': 1949,
 'treat': 2187,
 'per': 1547,
 'request': 1

## TF_IDF

In [36]:
df1=pd.read_csv('spam.csv',encoding='latin1')
df1=df1[['v1','v2']]
df1.columns=['label','message']
df1.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [37]:
import nltk
nltk.download('stopwords')
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
ws=WordNetLemmatizer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [38]:
corpus=[]
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z]',' ',df['message'][i])
    review=review.lower()
    review=review.split()
    review=[ws.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [39]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [40]:
## creating TF_IDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(max_features=100
                          )
X=cv.fit_transform(corpus).toarray()

In [41]:
X

array([[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.435, 0.000, 0.000, 0.461, 0.544, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.550, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.456

In [42]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,formatter=dict(float=lambda x: "{0:0.3f}".format(x)))

In [43]:
X

array([[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.435, 0.000, 0.000, 0.461, 0.544, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.550, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.456

In [44]:
tfidf=TfidfVectorizer(max_features=100,ngram_range=(1,2))
X1=tfidf.fit_transform(corpus).toarray()

In [45]:
tfidf.vocabulary_

{'go': 21,
 'great': 25,
 'got': 24,
 'wat': 89,
 'ok': 58,
 'free': 17,
 'win': 93,
 'text': 77,
 'txt': 85,
 'say': 68,
 'already': 0,
 'think': 80,
 'life': 37,
 'hey': 28,
 'week': 91,
 'back': 5,
 'like': 38,
 'still': 73,
 'send': 70,
 'friend': 18,
 'prize': 63,
 'claim': 8,
 'call': 6,
 'mobile': 48,
 'co': 9,
 'home': 30,
 'want': 88,
 'today': 82,
 'cash': 7,
 'day': 13,
 'reply': 65,
 'www': 96,
 'right': 66,
 'take': 75,
 'time': 81,
 'message': 45,
 'com': 10,
 'oh': 57,
 'yes': 99,
 'make': 43,
 'way': 90,
 'dont': 15,
 'miss': 47,
 'ur': 87,
 'going': 22,
 'da': 12,
 'lor': 39,
 'meet': 44,
 'really': 64,
 'know': 33,
 'love': 40,
 'amp': 2,
 'let': 36,
 'work': 94,
 'yeah': 97,
 'tell': 76,
 'thanks': 78,
 'uk': 86,
 'please': 61,
 'msg': 50,
 'see': 69,
 'pls': 62,
 'need': 52,
 'nokia': 55,
 'tomorrow': 83,
 'hope': 31,
 'well': 92,
 'lt': 41,
 'gt': 26,
 'lt gt': 42,
 'get': 19,
 'ask': 3,
 'morning': 49,
 'happy': 27,
 'sorry': 72,
 'give': 20,
 'new': 53,
 'find': 

In [46]:
y=pd.get_dummies(df1['label']
                 , drop_first=True
                 )

In [47]:
y

spam
0     False
1     False
2      True
3     False
4     False
...     ...
5567   True
5568  False
5569  False
5570  False
5571  False

[5572 rows x 1 columns]

In [57]:
## train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_bow,y,test_size=0.2,random_state=0)

# Naive bayes works well with sparse data

In [58]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [59]:
y_pred=spam_detect_model.predict(X_test)

In [60]:
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(Y_test,y_pred))

0.9829596412556054


In [61]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

       False       0.98      1.00      0.99       949
        True       0.98      0.90      0.94       166

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115



## Spam detection using TF_IDF

In [62]:
from sklearn.model_selection import train_test_split
X_train_tf,X_test_tf,Y_train_tf,Y_test_tf=train_test_split(X,y,test_size=0.2,random_state=0)

In [64]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train_tf,Y_train_tf)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [65]:
y_pred_2=spam_detect_model.predict(X_test_tf)

In [66]:
print(classification_report(Y_test_tf,y_pred_2))

              precision    recall  f1-score   support

       False       0.96      0.99      0.97       949
        True       0.92      0.73      0.82       166

    accuracy                           0.95      1115
   macro avg       0.94      0.86      0.89      1115
weighted avg       0.95      0.95      0.95      1115

